Global:
  use_gpu: false
  epoch_num: 3
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec/svtr_g/
  save_epoch_step: 100
  eval_batch_step:
  - 0
  - 200
  cal_metric_during_train: true
  pretrained_model: null
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words_en/word_10.png
  character_dict_path: null
  character_type: en
  max_text_length: 15
  infer_mode: false
  use_space_char: false
  save_res_path: ./output/rec/predicts_svtr_tiny.txt
  d2s_train_image_shape:
  - 3
  - 64
  - 256
Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.99
  epsilon: 1.0e-08
  weight_decay: 0.05
  no_weight_decay_name: norm pos_embed
  one_dim_param_no_weight_decay: true
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 2
Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
    name: STN_ON
    tps_inputsize:
    - 32
    - 64
    tps_outputsize:
    - 32
    - 100
    num_control_points: 20
    tps_margins:
    - 0.05
    - 0.05
    stn_activation: none
  Backbone:
    name: SVTR_G_Net
    img_size:
    - 32
    - 100
    out_char_num: 25
    out_channels: 192
    patch_merging: Conv
    embed_dim:
    - 64
    - 128
    - 128
    - 256
    depth:
    - 3
    - 3
    - 3
    - 3
    num_heads:
    - 2
    - 4
    - 4
    - 8
    mixer:
    - Local
    - Local
    - Local
    - Local
    - Local
    - Local
    - Global
    - Global
    - Global
    - Global
    - Global
    - Global
    local_mixer:
    - - 7
      - 11
    - - 7
      - 11
    - - 7
      - 11
    - - 7
      - 11
    last_stage: true
    prenorm: false
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
  Head:
    name: CTCHead
Loss:
  name: CTCLoss
PostProcess:
  name: CTCLabelDecode
Metric:
  name: RecMetric
  main_indicator: acc
Train:
  dataset:
    name: LMDBDataSet
    data_dir: ./datasets/rec/evaluation/
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - SVTRRecAug:
        aug_type: 1
    - CTCLabelEncode: null
    - SVTRRecResizeImg:
        image_shape:
        - 3
        - 64
        - 256
        padding: false
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: true
    batch_size_per_card: 384
    drop_last: true
    num_workers: 8
Eval:
  dataset:
    name: LMDBDataSet
    data_dir: ./datasets/rec/evaluation/
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode: null
    - SVTRRecResizeImg:
        image_shape:
        - 3
        - 64
        - 256
        padding: false
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 96
    num_workers: 2
profiler_options: null
